### ISSUE TITLE
Python version already exists when it is installing Python

### ISSUE THREAD

**Issue by joseangelsilvag** [fubarhouse/ansible-role-python#38]
I am trying to install only the Python version 2.7.15. So is set the variable `python_version` and `python_versions` with this value and it fails the first time because it is already instaled. 

```yaml
      install_pyenv: true
      install_python: true
      install_pypi: true
      pyenv_clean_install: false
      python_version: 2.7.15
      python_versions: 
       - 2.7.15
      python_packages:
```

The output error showed when I run this role is :

```
pyenv: /root/.pyenv/versions/2.7.15 already exists
+ [pyenv-install:160] read -p 'continue with installation? (y/N) 
```

The task involved is `"Python | Install Python"` and it joins both ansible vars `python_version` and `python_versions` causing this error.
